### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by freaky767** [snollygolly/sourceio-automation#10]
Whenever you are hacking somebody, and then the port closes, the bot just stays still, and does nothing, until you restart the bot, or you start hacking somebody.
Any fix?

**Comment by snollygolly** [comment]
Duplicate of #11. closing.

**Comment by freaky767** [comment]
but i opened this issue a lot earlier?

**Comment by snollygolly** [comment]
Doesn't matter, both are consolidated into one now.  It's the same root cause as well, one fix will fix them both.
