### ISSUE TITLE
Does the bot work?

### ISSUE THREAD

**Issue by freaky767** [snollygolly/sourceio-automation#12]
The bot for me, is stuck on trying to get the word, but it doesn't do anything.
Looking at the console, it fails to do the OCR.
Restarting the bot doesnt do anything.
Does the bot not work for me or did they patch it?

**Comment by freaky767** [comment]
![capture](https://user-images.githubusercontent.com/23425837/27967352-9b42d778-633a-11e7-8703-5ece21f91125.PNG)

**Comment by snollygolly** [comment]
See #8 
Did you get your own OCR API key?  It's required to make it work.

**Comment by freaky767** [comment]
how many letters is the ocr api key?

**Comment by freaky767** [comment]
i just pasted the key, and it doesnt work

**Comment by snollygolly** [comment]
As of Beta 2.2, they've overhauled word generation. I'm working to fix my bot, but I don't have an ETA.
