### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by yCozz** [snollygolly/sourceio-automation#19]
It types the word but it is wrong as if the image was updated or something. So I regenerated the DB and that did nothing to fix it. It appears with this update they patched most of everything. Even tho the regenerated DB wasn't the correct text to image, say if said "Data" the image would be "init" which i understand why it would, the images from updated DB and older DB were the same.

**Comment by snollygolly** [comment]
We have a PR (#17) that should resolve this issue.
