### ISSUE TITLE
Error When Trying to RE-Build

### ISSUE THREAD

**Issue by richard-lucky** [snollygolly/sourceio-automation#20]
C:\Users\TheBeast>cd C:\Users\TheBeast\Desktop\sourceio-automation-master\builder

C:\Users\TheBeast\Desktop\sourceio-automation-master\builder>npm install
builder@1.0.0 C:\Users\TheBeast\Desktop\sourceio-automation-master\builder
+-- bluebird@3.5.0
+-- co@4.6.0
+-- request@2.81.0
| +-- aws-sign2@0.6.0
| +-- aws4@1.6.0
| +-- caseless@0.12.0
| +-- combined-stream@1.0.5
| | `-- delayed-stream@1.0.0
| +-- extend@3.0.1
| +-- forever-agent@0.6.1
| +-- form-data@2.1.4
| | `-- asynckit@0.4.0
| +-- har-validator@4.2.1
| | +-- ajv@4.11.8
| | | `-- json-stable-stringify@1.0.1
| | |   `-- jsonify@0.0.0
| | `-- har-schema@1.0.5
| +-- hawk@3.1.3
| | +-- boom@2.10.1
| | +-- cryptiles@2.0.5
| | +-- hoek@2.16.3
| | `-- sntp@1.0.9
| +-- http-signature@1.1.1
| | +-- assert-plus@0.2.0
| | +-- jsprim@1.4.0
| | | +-- assert-plus@1.0.0
| | | +-- extsprintf@1.0.2
| | | +-- json-schema@0.2.3
| | | `-- verror@1.3.6
| | `-- sshpk@1.13.1
| |   +-- asn1@0.2.3
| |   +-- assert-plus@1.0.0
| |   +-- bcrypt-pbkdf@1.0.1
| |   +-- dashdash@1.14.1
| |   | `-- assert-plus@1.0.0
| |   +-- ecc-jsbn@0.1.1
| |   +-- getpass@0.1.7
| |   | `-- assert-plus@1.0.0
| |   +-- jsbn@0.1.1
| |   `-- tweetnacl@0.14.5
| +-- is-typedarray@1.0.0
| +-- isstream@0.1.2
| +-- json-stringify-safe@5.0.1
| +-- mime-types@2.1.15
| | `-- mime-db@1.27.0
| +-- oauth-sign@0.8.2
| +-- performance-now@0.2.0
| +-- qs@6.4.0
| +-- safe-buffer@5.1.1
| +-- stringstream@0.0.5
| +-- tough-cookie@2.3.2
| | `-- punycode@1.4.1
| +-- tunnel-agent@0.6.0
| `-- uuid@3.1.0
`-- request-promise@4.2.1
  +-- request-promise-core@1.1.1
  | `-- lodash@4.17.4
  `-- stealthy-require@1.1.1

npm WARN builder@1.0.0 No description
npm WARN builder@1.0.0 No repository field.

C:\Users\TheBeast\Desktop\sourceio-automation-master\builder>node index.js
module.js:472
    throw err;
    ^

Error: Cannot find module 'md5'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\TheBeast\Desktop\sourceio-automation-master\builder\index.js:4:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3

**Comment by yCozz** [comment]
I got you. Do "npm install md5" .

**Comment by snollygolly** [comment]
Yup, @ItsCozz is right.  totally forgot to save that package.
