### ISSUE TITLE
I can't change the message to the victim please help

### ISSUE THREAD

**Issue by notxenonbox** [snollygolly/sourceio-automation#31]
I don't know if it's me or anyone else has this problem but i can't change the message

**Comment by tiger0132** [comment]
You can change the message in the code (line 7)

**Comment by snollygolly** [comment]
Yep, like @tiger0132 said, you should be able to change the message here: https://github.com/snollygolly/sourceio-automation/blob/master/main.js#L7

If that doesn't work, feel free to re-open the issue.
