### ISSUE TITLE
New Minigame

### ISSUE THREAD

**Issue by BlueGhostAlt** [snollygolly/sourceio-automation#7]
An update happened to the game and now the hack doesn't work anymore

**Comment by bozoweed** [comment]
my bot is working come take in my github

**Comment by snollygolly** [comment]
I'll take a look at it.

**Comment by snollygolly** [comment]
Can you be more specific @TheSourceCod3Coder ?

I just loaded up the script and the newest version of the game and it works fine for me.

**Comment by bozoweed** [comment]
you can delete me snollygolly but you can't delete your bug ^^ and for you know , he got my link on mail so delete here is not delete on is mail ;) NO RAGE just leak

**Comment by bozoweed** [comment]
this is my link https://github.com/bozoweed/Bot-s0urce.io

**Comment by snollygolly** [comment]
Can't reproduce, closing.  Please re-open if you have more information.
