### ISSUE TITLE
POST http://api.ocr.space/parse/image 403 (Forbidden)

### ISSUE THREAD

**Issue by Bux42** [snollygolly/sourceio-automation#8]
Hello when I launche the bot there is this error

POST http://api.ocr.space/parse/image 403 (Forbidden)

**Comment by snollygolly** [comment]
Have you signed up at ocr.space for a free account? You must do that and use the API key they give you in the code.

**Comment by snollygolly** [comment]
I'm 99% sure this is the issue.  If this doesn't resolve your issue though, please re-open this issue and let me know.
