### ISSUE TITLE
Change port selection from static to random

### ISSUE THREAD

**Issue by freaky767** [snollygolly/sourceio-automation#9]
Can you make it so that it selects a random port each time and not just Port B?

**Comment by freaky767** [comment]
And if the port fails, it selects a different one.

**Comment by snollygolly** [comment]
Good suggestion. I'll see what I can do.

**Comment by freaky767** [comment]
Thanks

**Comment by freaky767** [comment]
If you could also make it, so it hacks any random person in the target list? That would be awesome.

**Comment by snollygolly** [comment]
It currently hacks the top person in the list.  My thinking on that is that if you're always attacking people higher than you, that's bound to help with rank.  If you attacked random people, I suspect it would take longer to get to the top.

**Comment by freaky767** [comment]
yeah...

**Comment by snollygolly** [comment]
@freaky767 check it out now and see if it works for you.  I tested it and it hacked a random port.  You may see it attack the same one multiple times in a row, but it should be somewhat random.
